/*
This code was autogenerated, 
it will regenerate with every change in blocks
*/
#include <application.h>

int button_click_count = 0;
int button_hold_count = 0;
int battery_percentage_value = 0;
float battery_voltage_value = 0;
float core_tmp112_value = 0;
float co2_value = 0;
float tag_humidity = 0;
twr_led_t led;
twr_button_t button;
twr_tmp112_t core_tmp112;
twr_tag_humidity_t humidity_tag;
twr_led_t gps_led_r;
twr_led_t gps_led_g;



void button_event_handler(twr_button_t *self, twr_button_event_t event, void *event_param) {
	if (event == TWR_BUTTON_EVENT_CLICK) {
		button_click_count++;
		twr_led_pulse(&led, 100);

		twr_radio_pub_push_button(&button_click_count);

	}
	else if (event == TWR_BUTTON_EVENT_HOLD) {
		button_hold_count++;
	}
}

void battery_event_handler(twr_module_battery_event_t event, void *event_param) {
	if (event == TWR_MODULE_BATTERY_EVENT_UPDATE) {
		float voltage;
		int percentage;
		if (twr_module_battery_get_voltage(&voltage) && twr_module_battery_get_charge_level(&percentage)) {
			battery_voltage_value = voltage;
			battery_percentage_value = percentage;
		}
		twr_radio_pub_int("battery/percentage", &battery_percentage_value);

	}
}

void core_tmp112_event_handler(twr_tmp112_t *self, twr_tmp112_event_t event, void *event_param) {
	if (event == TWR_TMP112_EVENT_UPDATE) {
		float value;
		if (twr_tmp112_get_temperature_celsius(self, &value)) {
			core_tmp112_value = value;
		}
		twr_radio_pub_temperature(TWR_RADIO_PUB_CHANNEL_R1_I2C0_ADDRESS_ALTERNATE, &core_tmp112_value);

	}
}

void co2_event_handler(twr_module_co2_event_t event, void *event_param) {
	if (event == TWR_MODULE_CO2_EVENT_UPDATE) {
		float value;
		if (twr_module_co2_get_concentration_ppm(&value)) {
			co2_value = value;
		}
		twr_radio_pub_co2(&co2_value);

	}
}

void humidity_tag_event_handler(twr_tag_humidity_t *self, twr_tag_humidity_event_t event, void *event_param) {
	if (event == TWR_TAG_HUMIDITY_EVENT_UPDATE) {
		float value;
		if (twr_tag_humidity_get_humidity_percentage(self, &value)) {
			tag_humidity = value;
		}
		twr_radio_pub_humidity(TWR_TAG_HUMIDITY_I2C_ADDRESS_DEFAULT, &tag_humidity);

	}
}

void gps_module_event_handler(twr_module_gps_event_t event, void *event_param)
{
    if (event == TWR_MODULE_GPS_EVENT_START)
    {
        twr_log_info("APP: Event TWR_MODULE_GPS_EVENT_START");

        twr_led_set_mode(&gps_led_g, TWR_LED_MODE_ON);
    }

    else if (event == TWR_MODULE_GPS_EVENT_STOP)
    {
        twr_log_info("APP: Event TWR_MODULE_GPS_EVENT_STOP");

        twr_led_set_mode(&gps_led_g, TWR_LED_MODE_OFF);
    }

    else if (event == TWR_MODULE_GPS_EVENT_UPDATE)
    {
        twr_led_pulse(&gps_led_r, 50);

        twr_module_gps_time_t time;

        if (twr_module_gps_get_time(&time))
        {
            char date[32];
            snprintf(date, sizeof(date), "%04d-%02d-%02d", time.year, time.month, time.day);
            twr_radio_pub_string("gps/date-time/date", date);

            char time_str[32];
            snprintf(time_str, sizeof(time_str), "%02d:%02d", time.hours, time.minutes);
            twr_radio_pub_string("gps/date-time/time", time_str);
        }

        twr_module_gps_position_t position;

        if (twr_module_gps_get_position(&position))
        {
            twr_radio_pub_float("gps/position/latitude", &position.latitude);
            twr_radio_pub_float("gps/position/longitude", &position.longitude);
        }

        twr_module_gps_altitude_t altitude;

        if (twr_module_gps_get_altitude(&altitude))
        {
            twr_radio_pub_float("gps/altitude", &altitude.altitude);

            char units[8];
            snprintf(units, sizeof(units), "%s", altitude.units == TWR_MODULE_GPS_EVENT_UPDATE ? "m" : "ft");
            twr_radio_pub_string("gps/altitude/units", units);
        }

        twr_module_gps_quality_t quality;

        if (twr_module_gps_get_quality(&quality))
        {
            twr_radio_pub_int("gps/quality/fix_quality", &quality.fix_quality);
            twr_radio_pub_int("gps/quality/satellites_tracked", &quality.satellites_tracked);
        }

        twr_module_gps_invalidate();
    }

    else if (event == TWR_MODULE_GPS_EVENT_ERROR)
    {
        twr_log_info("APP: Event TWR_MODULE_GPS_EVENT_ERROR");
    }
}

void application_init(void) {
	twr_log_init(TWR_LOG_LEVEL_DUMP, TWR_LOG_TIMESTAMP_ABS);
	twr_log_info("APPLICATION START");

	twr_led_init(&led, TWR_GPIO_LED, false, 0);
	twr_led_pulse(&led, 2000);

	twr_button_init(&button, TWR_GPIO_BUTTON, TWR_GPIO_PULL_DOWN, 0);
	twr_button_set_event_handler(&button, button_event_handler, NULL);

	twr_module_battery_init();
	twr_module_battery_set_event_handler(battery_event_handler, NULL);
	twr_module_battery_set_update_interval(5000);

	twr_tmp112_init(&core_tmp112, TWR_I2C_I2C0, TWR_TAG_TEMPERATURE_I2C_ADDRESS_ALTERNATE);
	twr_tmp112_set_event_handler(&core_tmp112, core_tmp112_event_handler, NULL);
	twr_tmp112_set_update_interval(&core_tmp112, 5000);

	twr_module_co2_init();
	twr_module_co2_set_update_interval(5000);
	twr_module_co2_set_event_handler(co2_event_handler, NULL);

	twr_tag_humidity_init(&humidity_tag, TWR_TAG_HUMIDITY_REVISION_R3, TWR_I2C_I2C0, TWR_TAG_HUMIDITY_I2C_ADDRESS_DEFAULT);
	twr_tag_humidity_set_event_handler(&humidity_tag, humidity_tag_event_handler, NULL);
	twr_tag_humidity_set_update_interval(&humidity_tag, 5000);

    if (!twr_module_gps_init())
    {
        twr_log_error("APP: GPS Module initialization failed");
    }

    else
    {
        twr_module_gps_set_event_handler(gps_module_event_handler, 5000);
        twr_module_gps_start();
    }

    twr_led_init_virtual(&gps_led_r, TWR_MODULE_GPS_LED_RED, twr_module_gps_get_led_driver(), 0);
    twr_led_init_virtual(&gps_led_g, TWR_MODULE_GPS_LED_GREEN, twr_module_gps_get_led_driver(), 0);

	twr_radio_init(TWR_RADIO_MODE_NODE_SLEEPING);
	twr_radio_pairing_request("twr-blockly-firmware", "blockly_dev");

}